In [33]:
data_list = [1 ,2 ,3]

In [34]:
data_list

[1, 2, 3]

In [35]:
import numpy as np

In [36]:
arr = np.array(data_list)

In [37]:
arr

array([1, 2, 3])

In [38]:
data_list_2 = [[10 ,20 ,30] ,[40 ,50 ,60] ,[70 ,80 ,90]]

In [39]:
arr2 = np.array(data_list_2)

In [40]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [41]:
arr

array([1, 2, 3])

In [42]:
arr[1]

2

In [43]:
arr[2]

3

In [44]:
arr2[2,2]

90

In [45]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [52]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [53]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
np.random.randint(10)

2

In [58]:
np.random.randint(1,10)

4

In [59]:
np.random.rand(10)

array([0.60984866, 0.86463695, 0.51783963, 0.90371296, 0.83737998,
       0.63618859, 0.66292341, 0.76003183, 0.7061314 , 0.0465184 ])

In [60]:
np.random.randn(10)

array([-1.48153147,  0.01339605,  0.08627166,  0.01463457,  0.54498634,
        0.81941456, -0.41815175,  0.43235667,  0.87201597, -0.62190597])

In [61]:
arr = np.arange(25)

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
arr.reshape(54)

ValueError: cannot reshape array of size 25 into shape (54,)

In [64]:
newArray = np.random.randint(1 ,100 ,10)

In [65]:
newArray

array([58, 50,  9, 32, 48, 22, 71, 58, 82, 94])

In [66]:
newArray.max()

94

In [68]:
newArray.min()

9

In [69]:
newArray.sum()

524

In [70]:
newArray.mean()

52.4

In [71]:
newArray.argmin()

2

In [72]:
newArray.argamax()

AttributeError: 'numpy.ndarray' object has no attribute 'argamax'

In [73]:
newArray.argmax()

9

In [79]:
detArray = np.random.randint(1,100,25)

In [80]:
detArray

array([56, 63, 35, 30, 75, 64, 56, 48, 21, 13, 89, 86, 81, 92, 28, 51, 44,
       50, 57, 62, 28, 50, 13, 11, 84])

In [81]:
detArray = detArray.reshape(5,5)

In [84]:
detArray

array([[56, 63, 35, 30, 75],
       [64, 56, 48, 21, 13],
       [89, 86, 81, 92, 28],
       [51, 44, 50, 57, 62],
       [28, 50, 13, 11, 84]])

In [85]:
np.linalg.det(detArray)

-36787562.000000045

In [87]:
round(np.linalg.det(detArray))

-36787562.0

In [89]:
detArray2 = np.array([[1,2] ,[2,3]])

In [90]:
round(np.linalg.det(detArray2))

-1.0

In [92]:
import numpy as np

In [93]:
arr = np.arange(1,10)

In [94]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr[1]

2

In [96]:
arr[2]

3

In [97]:
arr[1:5]

array([2, 3, 4, 5])

In [98]:
arr[:3]

array([1, 2, 3])

In [99]:
arr[::22]

array([1])

In [100]:
arr[::2]

array([1, 3, 5, 7, 9])

In [101]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr[:3]

array([1, 2, 3])

In [103]:
arr2 = arr.copy()

In [104]:
arr2[:3] = 25

In [105]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [106]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
newArray = np.arange(1,21)

In [120]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [121]:
newArray = newArray.reshape(4,5)

In [122]:
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [123]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [124]:
newArray[:2 ,:2]

array([[1, 2],
       [6, 7]])

In [125]:
newArray[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
arr = np.arange(1,10)

In [127]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [129]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [130]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr = np.arange(1,100)

In [132]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [134]:
arr[arr %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [135]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [136]:
np.zeros(%)

SyntaxError: invalid syntax (<ipython-input-136-1b05652e2e22>, line 1)

In [137]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [140]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [141]:
new = np.arange(1,17)

In [142]:
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [144]:
new = new.reshape(4,4)

In [145]:
new

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [146]:
np.eye(+)

SyntaxError: invalid syntax (<ipython-input-146-c5f56ef66b95>, line 1)

In [147]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [148]:
np.random.rand(5)

array([0.23384148, 0.64373716, 0.8468364 , 0.45174404, 0.21882106])

In [152]:
a = np.random.randn(25)

In [153]:
a

array([-0.11196863, -0.36102173,  0.52719521,  2.98024111, -1.19813224,
        0.306754  ,  0.39953446,  1.10129453,  0.20165615,  0.38978766,
        1.22078497,  0.03390063,  0.44492181,  0.2674031 ,  0.74030811,
       -1.84719799, -0.92226539, -0.11176405, -0.56684493, -1.0041866 ,
        0.18047914, -1.03030835, -0.50861641, -0.82085135,  0.88536092])

In [154]:
a = a.reshape(5,5)

In [155]:
a

array([[-0.11196863, -0.36102173,  0.52719521,  2.98024111, -1.19813224],
       [ 0.306754  ,  0.39953446,  1.10129453,  0.20165615,  0.38978766],
       [ 1.22078497,  0.03390063,  0.44492181,  0.2674031 ,  0.74030811],
       [-1.84719799, -0.92226539, -0.11176405, -0.56684493, -1.0041866 ],
       [ 0.18047914, -1.03030835, -0.50861641, -0.82085135,  0.88536092]])

In [158]:
new = np.linspace(1,20,5)

In [159]:
new

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])