In [2]:
import numpy as np
import pandas as pd 
from numpy.random import randn

In [4]:
randn(3,3)

array([[ 1.60915878, -0.59893588, -1.01274758],
       [ 0.25455751, -2.79031841, -1.46338496],
       [-0.9433811 , -1.48802219, -0.86846201]])

In [6]:
df = pd.DataFrame(data = randn(3,3) , index = ["A" ,"B" ,"C"] ,columns =["Column1" ,"Column2" ,"Column3"])

In [7]:
df

Column1   Column2   Column3
A  0.448092  0.856828  1.568645
B -0.943382  0.883448  0.305126
C  0.707099 -0.768671  0.278322

In [8]:
df["Column1"]

A    0.448092
B   -0.943382
C    0.707099
Name: Column1, dtype: float64

In [9]:
df["A"]

KeyError: 'A'

In [11]:
df.loc["A"]


Column1    0.448092
Column2    0.856828
Column3    1.568645
Name: A, dtype: float64

In [12]:
df["Column2"]

A    0.856828
B    0.883448
C   -0.768671
Name: Column2, dtype: float64

In [13]:
df.loc["B"]

Column1   -0.943382
Column2    0.883448
Column3    0.305126
Name: B, dtype: float64

In [14]:
df["Column4"] = pd.Series(data = randn(3) , index = ["A" ,"B" ,"C"])

In [15]:
df

Column1   Column2   Column3   Column4
A  0.448092  0.856828  1.568645  0.876365
B -0.943382  0.883448  0.305126  0.500485
C  0.707099 -0.768671  0.278322  1.501461

In [16]:
df["Column5"] = df["Column1"] + df["Column2"]

In [17]:
df

Column1   Column2   Column3   Column4   Column5
A  0.448092  0.856828  1.568645  0.876365  1.304920
B -0.943382  0.883448  0.305126  0.500485 -0.059934
C  0.707099 -0.768671  0.278322  1.501461 -0.061572

In [19]:
df.drop("Column5" ,axis=1)

Column1   Column2   Column3   Column4
A  0.448092  0.856828  1.568645  0.876365
B -0.943382  0.883448  0.305126  0.500485
C  0.707099 -0.768671  0.278322  1.501461

In [20]:
df.drop("Column4")

KeyError: "['Column4'] not found in axis"

In [21]:
df

Column1   Column2   Column3   Column4   Column5
A  0.448092  0.856828  1.568645  0.876365  1.304920
B -0.943382  0.883448  0.305126  0.500485 -0.059934
C  0.707099 -0.768671  0.278322  1.501461 -0.061572

In [23]:
df.drop("Column5" , axis = 1 ,inplace =True)

In [24]:
df

Column1   Column2   Column3   Column4
A  0.448092  0.856828  1.568645  0.876365
B -0.943382  0.883448  0.305126  0.500485
C  0.707099 -0.768671  0.278322  1.501461

In [25]:
df.loc["A"]

Column1    0.448092
Column2    0.856828
Column3    1.568645
Column4    0.876365
Name: A, dtype: float64

In [26]:
df.iloc[0]

Column1    0.448092
Column2    0.856828
Column3    1.568645
Column4    0.876365
Name: A, dtype: float64

In [27]:
df.loc["A" ,"Column1"]

0.448092366601389

In [28]:
df.loc[["A" ,"B"] , ["Column2" ,"Column3"]]

Column2   Column3
A  0.856828  1.568645
B  0.883448  0.305126

In [29]:
df = pd.DataFrame(data = randn(4,3) , index= ["A" ,"B" ,"C" ,"D"]  ,columns= ["Column1" ,"Column2" ,"Column3"])

In [30]:
df


Column1   Column2   Column3
A  0.241408 -0.733828  1.924027
B  1.064873 -1.320822  1.714811
C  1.491471  2.619146  1.890733
D -1.192635  0.331981  1.384608

In [31]:
df > 1

Column1  Column2  Column3
A    False    False     True
B     True    False     True
C     True     True     True
D    False    False     True

In [32]:
df[df > 1]

Column1   Column2   Column3
A       NaN       NaN  1.924027
B  1.064873       NaN  1.714811
C  1.491471  2.619146  1.890733
D       NaN       NaN  1.384608

In [33]:
df["Column1"] > 1

A    False
B     True
C     True
D    False
Name: Column1, dtype: bool

In [35]:
df[df["Column1"] > -1]

Column1   Column2   Column3
A  0.241408 -0.733828  1.924027
B  1.064873 -1.320822  1.714811
C  1.491471  2.619146  1.890733

In [36]:
df["Column4"] = ["m" ,"f" ,"ç" ,"d"]

In [38]:
df.set_index("Column4")

Column1   Column2   Column3
Column4                              
m        0.241408 -0.733828  1.924027
f        1.064873 -1.320822  1.714811
ç        1.491471  2.619146  1.890733
d       -1.192635  0.331981  1.384608

In [39]:
df

Column1   Column2   Column3 Column4
A  0.241408 -0.733828  1.924027       m
B  1.064873 -1.320822  1.714811       f
C  1.491471  2.619146  1.890733       ç
D -1.192635  0.331981  1.384608       d

In [41]:
df.set_index("Column4" ,inplace=True)

In [42]:
df

Column1   Column2   Column3
Column4                              
m        0.241408 -0.733828  1.924027
f        1.064873 -1.320822  1.714811
ç        1.491471  2.619146  1.890733
d       -1.192635  0.331981  1.384608

In [43]:
import numpy as np 
import pandas as pd
from numpy.random import randn

In [45]:
randn(3,3)

array([[ 0.5074203 ,  0.04711907,  0.29901584],
       [-1.10934981,  0.86498522,  1.76460086],
       [ 0.08728725, -1.56975395, -1.34054241]])

In [47]:
df = pd.DataFrame(data = randn(3 ,3) , index= ["Index1" ,"Index2" ,"Index3"] ,columns=["Column1" ,"Column2" ,"Column3"])

In [59]:
df

Column1   Column2   Column3
Index1 -0.209856  0.179080  0.563812
Index2 -0.368709  1.217714 -0.973220
Index3 -0.172625 -0.512370  0.444255

In [60]:
df["Column1"]

Index1   -0.209856
Index2   -0.368709
Index3   -0.172625
Name: Column1, dtype: float64

In [63]:
df.loc["Index1"]

Column1   -0.209856
Column2    0.179080
Column3    0.563812
Name: Index1, dtype: float64

In [64]:
df[["Column1" ,"Column2"]]

Column1   Column2
Index1 -0.209856  0.179080
Index2 -0.368709  1.217714
Index3 -0.172625 -0.512370

In [69]:
df["Column4"] = pd.Series(data = randn(3) ,index = ["Index1" ,"Index2" ,"Index3"] )

In [70]:
df["Column4"]

Index1   -0.898184
Index2    1.692824
Index3    0.010826
Name: Column4, dtype: float64

In [71]:
df

Column1   Column2   Column3   Column4
Index1 -0.209856  0.179080  0.563812 -0.898184
Index2 -0.368709  1.217714 -0.973220  1.692824
Index3 -0.172625 -0.512370  0.444255  0.010826

In [75]:
df.drop("Column4" ,inplace=True , axis=1)

In [76]:
df

Column1   Column2   Column3
Index1 -0.209856  0.179080  0.563812
Index2 -0.368709  1.217714 -0.973220
Index3 -0.172625 -0.512370  0.444255

In [77]:
df[["Column1" ,"Column2"]]

Column1   Column2
Index1 -0.209856  0.179080
Index2 -0.368709  1.217714
Index3 -0.172625 -0.512370

In [78]:
df.loc["Index1"]

Column1   -0.209856
Column2    0.179080
Column3    0.563812
Name: Index1, dtype: float64

In [79]:
df.iloc[0]

Column1   -0.209856
Column2    0.179080
Column3    0.563812
Name: Index1, dtype: float64

In [80]:
df.loc["Index1" ,"Column2"]

0.1790795056847232

In [82]:
df.loc["Index2" ,"Column2"]

1.217714305231827

In [83]:
df.loc[["Index1" ,"Index2"] ,["Column2" ,"Column3"]]

Column2   Column3
Index1  0.179080  0.563812
Index2  1.217714 -0.973220

In [84]:
import numpy as np 
import pandas as pd



In [87]:
arr = np.array([[10 ,20 ,np.nan] , [5 ,np.nan ,np.nan] ,[21 ,np.nan ,10]])

In [88]:
arr

array([[10., 20., nan],
       [ 5., nan, nan],
       [21., nan, 10.]])

In [89]:
df = pd.DataFrame(data = arr , index = ["Index1" ,"Index2" ,"Index3"] , columns = ["Column1" ,"Column2" ,"Column3"])

In [90]:
df

Column1  Column2  Column3
Index1     10.0     20.0      NaN
Index2      5.0      NaN      NaN
Index3     21.0      NaN     10.0

In [91]:
df.dropna()

Empty DataFrame
Columns: [Column1, Column2, Column3]
Index: []

In [92]:
df.dropna(thresh = 2)

Column1  Column2  Column3
Index1     10.0     20.0      NaN
Index3     21.0      NaN     10.0

In [94]:
df.dropna(axis = 1)

Column1
Index1     10.0
Index2      5.0
Index3     21.0

In [98]:
df.dropna(thresh = 1 ,axis= 1)

Column1  Column2  Column3
Index1     10.0     20.0      NaN
Index2      5.0      NaN      NaN
Index3     21.0      NaN     10.0

In [99]:
df

Column1  Column2  Column3
Index1     10.0     20.0      NaN
Index2      5.0      NaN      NaN
Index3     21.0      NaN     10.0

In [100]:
df.fillna(value = 100)

Column1  Column2  Column3
Index1     10.0     20.0    100.0
Index2      5.0    100.0    100.0
Index3     21.0    100.0     10.0

In [103]:
df.sum(axis =1)

Index1    30.0
Index2     5.0
Index3    31.0
dtype: float64

In [104]:
df.sum(axis = 1 ).sum()

66.0

In [105]:
df.sum().sum()

66.0

In [108]:
def calculateMean(df):
    totalSum = df.sum().sum()
    totalNum = df.size - df.isnull().sum().sum()
    return totalSum / totalNum

In [109]:
df.fillna(value = calculateMean(df))

Column1  Column2  Column3
Index1     10.0     20.0     13.2
Index2      5.0     13.2     13.2
Index3     21.0     13.2     10.0