In [1]:
data_list = [1 ,2 ,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [14]:
arr  = np.array(data_list)

In [15]:
arr

array([1, 2, 3])

In [6]:
data_list2 = [[10 ,20 ,30] ,[40 ,50 ,60] ,[70 ,80 ,90]]

In [11]:
arr2 = np.array(data_list2)

In [16]:
arr

array([1, 2, 3])

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
arr[1]

2

In [18]:
arr2[2]

array([70, 80, 90])

In [19]:
arr2[2][2]

90

In [20]:
arr2[2,2]

90

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(0,100 ,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.linspace(0 ,100 ,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.randint(0 ,10)

6

In [31]:
np.random.randint(10)

5

In [32]:
np.random.randn(10)

array([-1.46253749,  0.8419684 ,  0.38183968,  1.17454763,  1.00513855,
       -0.42221865,  0.4367856 ,  0.00996993, -0.15789506, -0.95254141])

In [35]:
np.random.randint(0 ,10 ,5)

array([9, 3, 4, 9, 2])

In [36]:
np.random.randn(10)

array([-1.12597941, -0.37791863, -0.27509853,  1.61738763,  1.17909746,
       -0.95378587, -0.78893833,  0.8660296 ,  0.36789069, -1.62356123])

In [38]:
np.random.randint(10,20 ,7)

array([14, 11, 10, 17, 19, 10, 16])

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
newArray = np.random.randint(1,100,10)

In [45]:
newArray = np.random.randint(1 ,100 ,10)

In [46]:
newArray

array([33, 14, 57, 90, 68, 74, 28, 17, 40,  2])

In [47]:
newArray.max()

90

In [48]:
newArray.min()

2

In [49]:
newArray.sum()

423

In [50]:
newArray.mean()

42.3

In [51]:
newArray.argmin()

9

In [52]:
newArray.argmin()

9

In [53]:
newArray.argmax()

3

In [54]:
newArray

array([33, 14, 57, 90, 68, 74, 28, 17, 40,  2])

In [55]:
detArray = np.random.randint(1 ,100 ,25)

In [56]:
detArray

array([21, 55, 54, 62, 46, 67, 48, 42, 92, 31, 73, 17, 59, 42, 76, 99, 75,
       59, 19, 35, 58, 57, 85, 98,  5])

In [57]:
detArray = detArray.reshape(5,5)

In [58]:
detArray

array([[21, 55, 54, 62, 46],
       [67, 48, 42, 92, 31],
       [73, 17, 59, 42, 76],
       [99, 75, 59, 19, 35],
       [58, 57, 85, 98,  5]])

In [59]:

np.linalg.det(detArray)

-1415362816.0000021

In [60]:
round(np.linalg.det(detArray))

-1415362816.0

In [61]:
detArray2 = np.array([[1,2] ,[3,4]])

In [62]:
round(np.linalg.det(detArray2))

-2.0

In [63]:
import numpy as np

In [64]:
arr = np.arange(1 ,10)

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[1]

2

In [67]:
arr[1:3]

array([2, 3])

In [68]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[::2]

array([1, 3, 5, 7, 9])

In [70]:
arr2 = arr.copy()

In [73]:
arr2[2]  = 4

In [74]:
arr2

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

In [75]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
newArray = np.arange(0,20)

In [83]:
newArray = newArray.reshape(4,5)

In [84]:
newArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
newArray[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [87]:
newArray[:2 ,:2]

array([[0, 1],
       [5, 6]])

In [88]:
newArray[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [89]:
arr = np.arange(1 ,10)

In [90]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [92]:
arr[arr > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [93]:
import numpy as np 

In [101]:
arr1 = np.array([10 ,20 ,30 ,40 ,50])
arr2 = np.array([2 ,3 ,4 ,5 ,6])

In [102]:
arr1

array([10, 20, 30, 40, 50])

In [103]:
arr2

array([2, 3, 4, 5, 6])

In [104]:
arr1 + arr2

array([12, 23, 34, 45, 56])

In [105]:
arr1 -arr2 

array([ 8, 17, 26, 35, 44])

In [106]:
arr2 **2

array([ 4,  9, 16, 25, 36], dtype=int32)

In [107]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [108]:
import numpy as np

In [109]:
import pandas as pd

In [110]:
label_list = ["Mustafa" ,"Ali" ,"Kemal" ,"Kadir" ,"Zeynep"]